apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: temptest
  labels:
    app: nginx
    task-group: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        task_group: pod
    spec:
      containers:
        - name: nginx
          image: nginx:bookworm
          # command: [""]
          ports:
          - containerPort: 80
          volumeMounts:
            - name: index-html
              mountPath: "/usr/share/nginx/html"
            - name: default-conf
              mountPath: "/etc/nginx/sites-enabled"
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
      volumes:
        - name: index-html
          configMap:
            name: index-html
            items:
              - key: index-html
                path: index.html
        - name: default-conf
          configMap:
            name: default-conf
            items:
              - key: nginx
                path: default.conf
      