apiVersion: batch/v1
kind: Job
metadata:
  name: jobtest
  namespace: temptest
  labels:
    task-group: job
spec:
  template:
    metadata:
      labels:
        task-group: job
    spec:
      restartPolicy: Never
      containers:
      - name: jobtest
        image: python
        command:
        - python3
        - -c
        - |
          import os, sys
          print("Hello world")
          if int(os.environ.get("JOB_COMPLETION_INDEX")) % 2 == 0:
            sys.exit(1) 