apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: nginx
  labels:
    team: app

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: index-html
    files:
      - index-html
  - name: default-conf
    files:
      - nginx