apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: kube-prometheus-stack
  name: kubepodnotreadytaskgroup
  namespace: temptest
spec:
  groups:
  - name: kubepodtestalert
    rules:
    - alert: KubePodNotReadyTeam
      annotations:
        description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes..
        summary: Not ready
      expr: (kube_statefulset_status_replicas_ready{job="kube-state-metrics",namespace="monitoring",statefulset="alertmanager-kube-prometheus-stack-alertmanager"}) == 1
      for: 30s
      labels:
        severity: warning
        task_group: "{{ with printf `kube_statefulset_labels{namespace='%s',statefulset='%s'}` .Labels.namespace .Labels.statefulset | query }}{{ with (. | first).Labels.label_task_group }}{{ . }}{{end}}{{end}}"

## kube_namespace_labels * on (namespace) group_right (label_task_group) ##
## working query ##
## {{ with printf `kube_namespace_labels{namespace="%s"}` .Labels.namespace | query }}{{ with (. | first).Labels.label_task_group }}{{ . }}{{end}}{{end}} ##