apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: temptest
  labels:
    app: nginx
    task-group: service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 80
  - name: metrics
    port: 9113
    protocol: TCP