apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: temptest
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          - name: metrics
            containerPort: 9113
            protocol: TCP
          volumeMounts:
            - name: index-html
              mountPath: "/usr/share/nginx/html"
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
      volumes:
        - name: index-html
          configMap:
            name: index_html
            items:
              - key: index-html
                path: index.html
      